name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Specify the Node.js version you want

      - name: Install NPM packages
        run: npm install

      - name: Build
        run: npm run build # This runs the "wp-scripts build" command

      - name: Remove files and folders based on .distignore
        run: cat .distignore | xargs rm -rf

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          body: "Description of the release"
          # Attach files to the release if needed
          # You can use actions/upload-release-asset for this purpose
